package ChatApplication;


/**
* ChatApplication/ChatMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Dienstag, 23. April 2019 21:49 Uhr MESZ
*/

public final class ChatMessage implements org.omg.CORBA.portable.IDLEntity
{
  public String nickname = null;
  public String text = null;

  public ChatMessage ()
  {
  } // ctor

  public ChatMessage (String _nickname, String _text)
  {
    nickname = _nickname;
    text = _text;
  } // ctor

} // class ChatMessage
