package ChatApplication;

/**
* ChatApplication/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Dienstag, 23. April 2019 21:49 Uhr MESZ
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatApplication.Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (ChatApplication.Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatApplication.ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatApplication.ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatApplication.ClientHelper.type ();
  }

}
