package ChatApplication;


/**
* ChatApplication/ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Dienstag, 23. April 2019 21:49 Uhr MESZ
*/

public interface ClientOperations 
{
  void message (ChatApplication.ChatMessage msg);
  void join (ChatApplication.ChatMessage msg);
  void leave (ChatApplication.ChatMessage msg);
  void putHistory (ChatApplication.ChatMessage[] history);
} // interface ClientOperations
