package ChatApplication;


/**
* ChatApplication/ClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Dienstag, 23. April 2019 21:49 Uhr MESZ
*/

public abstract class ClientPOA extends org.omg.PortableServer.Servant
 implements ChatApplication.ClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("message", new java.lang.Integer (0));
    _methods.put ("join", new java.lang.Integer (1));
    _methods.put ("leave", new java.lang.Integer (2));
    _methods.put ("putHistory", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ChatApplication/Client/message
       {
         ChatApplication.ChatMessage msg = ChatApplication.ChatMessageHelper.read (in);
         this.message (msg);
         out = $rh.createReply();
         break;
       }

       case 1:  // ChatApplication/Client/join
       {
         ChatApplication.ChatMessage msg = ChatApplication.ChatMessageHelper.read (in);
         this.join (msg);
         out = $rh.createReply();
         break;
       }

       case 2:  // ChatApplication/Client/leave
       {
         ChatApplication.ChatMessage msg = ChatApplication.ChatMessageHelper.read (in);
         this.leave (msg);
         out = $rh.createReply();
         break;
       }

       case 3:  // ChatApplication/Client/putHistory
       {
         ChatApplication.ChatMessage history[] = ChatApplication.chathistoryHelper.read (in);
         this.putHistory (history);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatApplication/Client:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Client _this() 
  {
    return ClientHelper.narrow(
    super._this_object());
  }

  public Client _this(org.omg.CORBA.ORB orb) 
  {
    return ClientHelper.narrow(
    super._this_object(orb));
  }


} // class ClientPOA
