package ChatApplication;


/**
* ChatApplication/HistoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Dienstag, 23. April 2019 21:49 Uhr MESZ
*/

public interface HistoryOperations 
{
  ChatApplication.ChatMessage[] getNMessages (short numberOfmessages);
  void message (ChatApplication.ChatMessage message);
} // interface HistoryOperations
