package ChatApplication;


/**
* ChatApplication/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Dienstag, 23. April 2019 21:49 Uhr MESZ
*/

public interface ServerOperations 
{
  boolean attach (String nickname, ChatApplication.Client ref);
  boolean detach (String nickname);
  boolean attachHistory (ChatApplication.History ref);
  void _notify (ChatApplication.ChatMessage msg);
} // interface ServerOperations
