package ChatApplication;


/**
* ChatApplication/ServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Dienstag, 23. April 2019 21:49 Uhr MESZ
*/

public abstract class ServerPOA extends org.omg.PortableServer.Servant
 implements ChatApplication.ServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("attach", new java.lang.Integer (0));
    _methods.put ("detach", new java.lang.Integer (1));
    _methods.put ("attachHistory", new java.lang.Integer (2));
    _methods.put ("notify", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ChatApplication/Server/attach
       {
         String nickname = in.read_string ();
         ChatApplication.Client ref = ChatApplication.ClientHelper.read (in);
         boolean $result = false;
         $result = this.attach (nickname, ref);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ChatApplication/Server/detach
       {
         String nickname = in.read_string ();
         boolean $result = false;
         $result = this.detach (nickname);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ChatApplication/Server/attachHistory
       {
         ChatApplication.History ref = ChatApplication.HistoryHelper.read (in);
         boolean $result = false;
         $result = this.attachHistory (ref);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // ChatApplication/Server/_notify
       {
         ChatApplication.ChatMessage msg = ChatApplication.ChatMessageHelper.read (in);
         this.notify (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatApplication/Server:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Server _this() 
  {
    return ServerHelper.narrow(
    super._this_object());
  }

  public Server _this(org.omg.CORBA.ORB orb) 
  {
    return ServerHelper.narrow(
    super._this_object(orb));
  }


} // class ServerPOA
